# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='anwser',
            field=models.CharField(choices=[('a', 'a.'), ('b', 'b.'), ('c', 'c.'), ('d', 'd.')], max_length=1),
        ),
    ]
