# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=100)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('anwser', models.CharField(choices=[('a', 'a.'), ('b', 'b.'), ('c', 'c.'), ('d', 'd.')], max_length=1)),
            ],
        ),
    ]
