# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BigIntegerField', models.BigIntegerField(blank=True, null=True)),
                ('BooleanField', models.BooleanField(default=True)),
                ('CharField', models.CharField(blank=True, max_length=10, null=True)),
                ('DateField', models.DateField(blank=True, null=True)),
                ('DateTimeField', models.DateTimeField(blank=True, null=True)),
                ('DecimalField', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('EmailField', models.EmailField(blank=True, max_length=254, null=True)),
                ('FileField', models.FileField(blank=True, null=True, upload_to=b'')),
                ('FilePathField', models.FilePathField(blank=True, null=True)),
                ('FloatField', models.FloatField(blank=True, null=True)),
                ('ImageField', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('IntegerField', models.IntegerField(blank=True, null=True)),
                ('GenericIPAddressField', models.GenericIPAddressField(blank=True, null=True)),
                ('NullBooleanField', models.NullBooleanField()),
                ('PositiveIntegerField', models.PositiveIntegerField(blank=True, null=True)),
                ('PositiveSmallIntegerField', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('SlugField', models.SlugField(blank=True, null=True)),
                ('SmallIntegerField', models.SmallIntegerField(blank=True, null=True)),
                ('TextField', models.TextField(blank=True, null=True)),
                ('TimeField', models.TimeField(blank=True, null=True)),
                ('URLField', models.URLField(blank=True, null=True)),
                ('x', models.DecimalField(decimal_places=2, max_digits=3)),
                ('y', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='ForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
    ]
